config/routes.rb
Rails.application.routes.draw do
    resources :orders, only: [:index, :show, :create, :new]

    #get 'home/index'
    devise_for :users, :controllers => {:registrations => "registrations"}

    # :skip => :registerable
    devise_scope :user do
      get 'signup', to: 'devise/registrations#new'
    end

    devise_scope :user do
      get 'login', to: 'devise/sessions#new'
    end
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    root to: 'home#index'

    resources :products, only: [:index, :show, :new, :create, :destroy, :edit]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :users
  belongs_to :products
end

app/models/product.rb
require 'monetize'

class Product < ApplicationRecord
  mount_uploader :photo, PhotoUploader
  monetize :asking_price_cents

  validates :photo, presence: true
  validates :asking_price_cents, presence: true
  validates :title, presence: true
  validates :description, length: { maximum: 44,
      too_long: "%{count} characters is the maximum allowed" }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable, :registerable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception, prepend: true
end

app/controllers/concerns/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit( :name,
                                  :email,
                                  :password,
                                  :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit( :name,
                                  :email,
                                  :password,
                                  :password_confirmation,
                                  :current_password)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_user!, only: [:create]

  def index
    @order = Order.all
  end

  def show
    @product = Product.find(params[:id])
  end

  def create
    # see if you sent the product_id param
    # create an order
    # update the product (add the order id to it)
    # redirect user somewhere
  end

  def new
    #provides form
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_user!, only: [:create]

  def index
    @products = Product.all
  end

  def show
    @product = Product.find(params[:id])
  end

  def new
    @product = Product.new
  end

  def edit
    @product = Product.find(params[:id])
  end

  def create
    @product = Product.new(product_params)

    @product.save!
    redirect_to @product
  end

  # def update
  # end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy

    redirect_to products_path
  end

  private

  def product_params
    params.require(:product).permit(:title, :description, :photo, :asking_price)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
  def products_helper(product)
    product.photo.present? ? product.photo : ""
  end
end

app/views/home/index.html.erb
<body>
  <div class="header_logo">
    <h1>Pop Shop</h1>
    <p>Miami</p>
  </div>
  <div class="banner">
    <div class="container banner1">
        <div class="text-block">
          <h3>Specialty gifts from all over the world</h3>
            <p>Forgot to buy that special someone a gift on your travels? Turn that Oops into an Ohh lala</p>
        </div>
        <div class="start-shopping-link"><h2 ><%= link_to 'New Arrivals', products_path %></h2>
        </div>
      </div>
    </div>
    <div class="container">
      <div class="product-showcase">
        <%= link_to products_path do %>
          <h2 class="large-banner-pic">Delicacy</h2>
            <%= cl_image_tag("cupcakes2.jpg", :transformation=>[
            {:width=>688, :height=>384, :crop=>"fill"}
            ]) %>
        <% end %>
        <%= link_to products_path do %>
          <h2 class="small-banner-pic">Splurge</h2>
            <%= cl_image_tag("purse9.jpg", width: 384, height: 384, crop: :fill) %>
        <% end %>
      </div>
    </div>
  </div>
    <div class="container">
      <div class="product-showcase1">
        <%= link_to products_path do %>
          <h2 class="small-banner-pic">Indulge</h2>
        <%= cl_image_tag("feiyue_shoes.jpg", width: 384, height: 384) %>
        <% end %>
        <%= link_to products_path do %>
          <h2 class="large-banner-pic">Gourmet Beans</h2>
        <%= cl_image_tag("coffee.jpg", width: 688, height: 384, crop: :fill) %>
        <% end %>
      </div>
    </div>
    <div class="container">
    </div>
</body>

app/views/layouts/application.html.erb
<!doctype html>
<html>
  <head>
    <title>PopShop</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Philosopher:400,700|Poiret+One" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt" crossorigin="anonymous">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

  <body>

    <%= render "shared/newnavbar" %>

    <div class="ps-content">
      <%= yield %>
    </div>

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

app/views/orders/index.html.erb
<div class="container">
  <h1>All Previous Orders</h1>
  <p><%= @product %></p>
</div>

app/views/orders/show.html.erb
<div class="container order-confirmation">
    <h1> Order Confirmation</h1>
      <p> Your <%= @product.title %> should arrive in 3 - 5 business days </p>
      <%= cl_image_tag @product.photo, width: "50%" %>
      <p> Thank you for shopping with us!</p>
  </div>
</div>

app/views/products/_new_product_form.html.erb
<%= form_with scope: :product, url: products_path, local: true do |form| %>
    <p>
      <%= form.label :title %><br>
      <%= form.text_field :title %>
    </p>

    <p>
      <%= form.label :description %><br>
      <%= form.text_area :description %>
    </p>

    <p>
      <%= form.file_field :photo %>
    </p>

    <p>
      <%= form.label :asking_price %><br>
      <%= form.text_field :asking_price %>
    </p>

    <p>
      <%= form.submit %>
    </p>
  <% end %>

app/views/products/_textimage.html.erb
<div class="col-xs=12 col-sm-4">
  <tr>
    <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= cl_image_path products_helper(product) %>') ">
      <div class="card-description"><h2 class="product-title"><%= link_to product.title, product_path(product) %></h2>
        <h3 class="description">
        <%= product.description %>
          <p class="price">
          <%= product.asking_price %>
          </p>
        </h3>
      </div>
    </div>
  </tr>
</div>

app/views/products/edit.html.erb
<div class="container">
  <div class="editing">
  <h1>Edit Product</h1>
  <%= render "new_product_form" %>
  <button type="button" class="edit-btn"><%= link_to "Nevermind everything looks great!", product_path %></button>
  </div>
</div>

app/views/products/index.html.erb
<div class="container">
<h1>Pop Shop Goodies </h1>
    <div class="cards">
      <div class="row">
      <% @products.each do |product| %>
        <%= render "products/textimage", product:product %>
      <% end %>
      </div>
    </div>
    <div>
      <h3 ><%= link_to 'Add New Item', new_product_path %></h3>
    </div>
</div>

app/views/products/new.html.erb
<div class="container">
  <h1 class="new-product-page">New Product</h1>
  <p>Add new product to website</p>
  <%= render "new_product_form" %>
</div>

app/views/products/show.html.erb
<div class="container">
  <div class="show-title">
    <h1><%= @product.title %></h1>
  </div>
  <div>
  </div>
  <div class="show-essential">
    <div class="show-photo">
      <% if @product.photo.present? %>
        <%= cl_image_tag @product.photo, height: 400, width: 500, crop: :fill %>
      <% end %>
      <p>
        <% @product.photo %>
      </p>
    </div>
    <div class="product-description">
      <p>
        <%= @product.description %>
      </p>
      <p>$
        <%= @product.asking_price %>
      </p>

    <!-- Modal -->
    <!-- Button trigger modal -->
    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModalCenter">
      Purchase
    </button>

    <!-- Modal -->
      <div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="PSModalTitle">SHOPPING BAG</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">
              <p><b><%= @product.title %></b></p>
              <p>Qty 1</p>
              <p><b>$<%= @product.asking_price %></b></p>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-dismiss="modal">Continue Shopping</button>
              <button type="button" class="btn btn-primary ps-payment"><%= link_to 'Proceed to Payment', order_path %></button>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <h3 ><%= link_to 'Edit', edit_product_path %></h3>
</div>

<script>
  document.onready(function() {
    console.log("Starbucks Wifi")
  })
</script>

app/views/shared/_footer.html.erb
<div class="ps-footer">
  <div class="container">
    Made by Dania
  </div>
</div>

app/views/shared/_newnavbar.html.erb
<div class="ps-navbar">
  <div>
    <a href="/">
      <%= image_tag "popshop-logo.png", alt:"Pop Shop logo", height: "40px" %>
    </a>
  </div>
  <!-- <div class="ps-navbar-items" style="width: 700px"> -->
  <div class="ps-navigation">
    <div>
     <%= link_to products_path do %>
        <i class=" fas fa-search"></i>  Discover
      <% end %>
    </div>
    <div>
      <%= render "shared/user_dropdown" %>
    </div>
  </div>
</div>

app/views/shared/_user_dropdown.html.erb
<% if user_signed_in? %>
  <div class="dropdown">
    <button class="btn btn-secondary btn-sm dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      Account
    </button>
    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
      <%= link_to 'Edit Profile',
      edit_user_registration_path,
      class: "dropdown-item" %>

      <%= link_to 'Log out',
      destroy_user_session_path,
      method: :delete,
      class: "dropdown-item" %>
    </div>
  </div>
  <% else # user not signed it %>
    <i class="fas fa-lock"></i>
    <%= link_to 'Login', login_path %>
    <i class="fas fa-user-circle"></i>
    <%= link_to 'Signup', signup_path %>
<% end # if user is signed it %>